extends:
  # - eslint:recommended
  - plugin:astro/recommended
  # - plugin:jsx-a11y/recommended
  # - plugin:import/recommended
  # - plugin:import/typescript
  - prettier
overrides:
  # Define the configuration for `.astro` file.
  - files:
      - '*.astro'
    # Allows Astro components to be parsed.
    parser: astro-eslint-parser
    # Parse the script in `.astro` as TypeScript by adding the following configuration.
    # It's the setting you need when using TypeScript.
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .astro
    rules: {}
  - files:
    - '*.svelte'
    processor: svelte3/svelte3
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .svelte
    rules: {}
    settings:
      svelte3/typescript: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - svelte3
  - '@typescript-eslint'
ignorePatterns:
  - './dist/**/*'
  - './node_modules/**/*'
settings: {}
