extends:
  - eslint:recommended
  - plugin:astro/recommended
  - plugin:svelte/recommended
  # - plugin:jsx-a11y/recommended
  # - plugin:import/recommended
  # - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files:
      - '*.astro'
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .astro
    rules: {}
  - files:
    - '*.svelte'
    parser:  svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .svelte
    rules: {}
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - './dist/**/*'
  - './node_modules/**/*'
settings: {}
rules: {
  no-undef: off,
  no-unused-vars: warn
}
